Make architecture configurable
gardenlinux/package-build pull request #13
Opened 2024-11-08 12:17 UTC by toanju

**What this PR does / why we need it**:

This makes the architecture variable configurable. Since we would like to skip the ARM64 builds.

2024-11-08 13:26 UTC, nkraetzschmar approved these changes
lgtm

2024-11-08 13:28 UTC, nkraetzschmar requested changes
making the arch in the build step optional looks fine, but this will break in the release step when trying to download the binary-arm64 artifact and it does not exist

you'd need to add some conditional logic there as well

2024-11-08 13:50 UTC, toanju commented
right, put it to draft and will check how to fix this, thanks!

2024-11-08 15:29 UTC, toanju commented
applied the matrix build to the release as well

2024-11-09 10:59 UTC, toanju commented
As discussed offline, the release can't be run in a build matrix, hence added if to the arm64/amd64 steps that check the architecture passed.

2024-11-11 15:30 UTC, nkraetzschmar approved these changes
all good now :+1:

2024-11-11 15:30 UTC, merged